apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-wallet-api
  labels:
    app: treetracker-wallet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-wallet-api
  template:
    metadata:
      labels:
        app: treetracker-wallet-api
    spec:
      initContainers:
      - name: "wallet-db-migration-job-init"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: Always
        args: 
        - "job"
        - "wallet-db-migration-job"
      containers:
      - name: treetracker-wallet-api
        image: greenstand/treetracker-wallet-api:latest
        ports:
        - containerPort: 80
        env:
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: treetracker-wallet-jwt-keys
                key: private-key
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: treetracker-wallet-jwt-keys
                key: public-key
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: treetracker-api-database-connection
                key: db
          - name: DATABASE_SCHEMA
            valueFrom:
              secretKeyRef:
                name: treetracker-api-database-connection
                key: schema
          - name: NODE_LOG_LEVEL
            value: debug
