apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-wallet-api
  labels:
    app: treetracker-wallet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-wallet-api
  template:
    metadata:
      labels:
        app: treetracker-wallet-api
    spec:
      containers:
      - name: treetracker-wallet-api
        image: greenstand/treetracker-wallet-api:1.0.0-latest
        ports:
        - containerPort: 80
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: treetracker-api-jwt
                key: jwt
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: treetracker-api-database-connection
                key: db
